version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  api:
    build: ./api
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/suba
      - JWT_SECRET=supersecret
      - ORIGIN=http://localhost:8081
    ports:
      - '4000:4000'
volumes:
  mongo-data:
